### PR TITLE
added verable info this info is by wiibrew

### PR DESCRIPTION
**Pull request by erikiorai**
so I found more info about how vote.cgi works by wiibrew http://wiibrew.org/wiki/Everybody_Votes_Channel

### CODE REVIEW

**Comment by AwesomeMarioFan** [comment]
The commit doesn't seem to make any changes to vote.php.

**Comment by erikiorai** [comment]
click view

**Comment by erikiorai** [comment]
idk why happend im used notepad++

**Comment by AwesomeMarioFan** [comment]
The commit is showing 0 added lines and 0 removed lines - which means there are no changes that you made to the file. Make sure you save the changes in Notepad++ first, then make/push the commit.

**Comment by KcrPL** [comment]
Seriously?

>$typeCD = [];
$questionID = [];
$wiiNo = [];
$CountryID = [];
$RegionID = [];
$ansCNT = [];

That variables does **nothing**. And they probably won't be even used when making EVC.

**Comment by KcrPL** [comment]
@AwesomeMarioFan (https://github.com/Fun4TubeGr/VTP/blob/d3992ff71d545d090292d41b123cb5ad9836b943/vote.php)

**Comment by AwesomeMarioFan** [comment]
@KcrPL Ah I see now.

**Comment by kevinbioj** [comment]
You do realize that a variable you do not use is a **useless** variable, right ? XD
It won't change anything except creating these vars that contains nothing.

**Comment by AwesomeMarioFan** [comment]
I think the variables should be added after we are able to write the code to use them.

**Comment by KcrPL** [comment]
@AwesomeMarioFan ~~Are you even able to utilize that variables?~~

**Comment by spotlightishere** [comment]
Hi,

Thanks for showing an interest in VTP. These commits make no functional changes, even as far as design.

Please stop making such PRs, or we will block you from our GitHub.

**Comment by KcrPL** [comment]
Lol, don't know what to say so take a look at that dancing gif (Gif's can't dance obviously)

**Comment by Artuto** [comment]
@spotlightishere HOW DO YOU DARE ON CLOSSING THIS BRILLANT SOFTWARE PR

**Comment by erikiorai** [comment]
@spotlightishere i know that verable cant channge ervything  but is one step coding to get work evrybory votes channel

**Comment by therealprocyon** [comment]
@Fun4TubeGr are you trolling? It looks to me that you are. Anyhow, if you don't know how it works, then don't try to code for it. Anyhow, I suggest you revert the changes in your fork/history, because if, and I say IF, you ever start writing good code and you commit to RC24 there'd be a chance of you accidentally adding these failed changes as well.

**Comment by erikiorai** [comment]
No im not trolling i found this on wiibrew

**Comment by spotlightishere** [comment]
That variable does nothing by itself. There is no functional use.

**Comment by KcrPL** [comment]
@Fun4TubeGr If you want use that variables, you need a code for that. In that script there are no code that could utilize that variables.

**Comment by erikiorai** [comment]
Yea i know that but this is wat verabels uses vote.cgi

**Comment by kevinbioj** [comment]
Yes, but creating a var you do not use is useless.
It's like buying a car you won't drive

**Comment by spotlightishere** [comment]
Reasons why not merged stated many times above.

**Pull request closed without merging**
