### PR TITLE
You frogot adding info about this

### PR DESCRIPTION
**Pull request by erikiorai**
So i updated info about vtp

### CODE REVIEW

**Comment by spotlightishere** [comment]
Thanks for the PR, at this time we won't update as the actual scripts are being developed.

**Comment by erikiorai** [comment]
Yea but i dont gives error code 23000

**Comment by spotlightishere** [comment]
Indeed it doesn't, but we'd rather update the actual scripts and describe all at once.

**Comment by erikiorai** [comment]
Ok

**Pull request closed without merging**
